model_name_or_path: /root/autodl-tmp/qwen25-week4/best_model/qwen25-7b-week4-dpo-corrective-merged
stage: sft
do_train: true
do_eval: true
finetuning_type: lora
lora_target: all
quantization_bit: 4
quantization_type: nf4
double_quantization: true
gradient_checkpointing: true
dataset: week6_tool_sft_train
eval_dataset: week6_tool_sft_eval_frozen
dataset_dir: /root/autodl-tmp/qwen25-week6/day31/data
template: qwen
cutoff_len: 2048
max_samples: null
overwrite_cache: true
preprocessing_num_workers: 4
output_dir: /root/autodl-tmp/qwen25-week6/day31/runs/tool-sft-lora
logging_steps: 1
save_steps: 25
eval_steps: 25
save_total_limit: 2
plot_loss: true
overwrite_output_dir: false
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
use_unsloth: false
seed: 42
